### PR TITLE
Minor fixes to cbcf.VariantRecord

### PR DESCRIPTION
**Pull request by bioinformed**

### CODE REVIEW

**Comment by bioinformed** [comment]
CI failure seems to be spurious and caused by a sporadic environment failure.

**Comment by AndreasHeger** [comment]
Thanks!

**Comment by bioinformed** [comment]
Thanks!  Working on pysam is now a part of my day job, so expect more updates in the coming weeks.  (I've moved from 23andMe to Helix as of this week.)

**Comment by AndreasHeger** [comment]
That is good news, certainly for pysam! All the best in your new post.

Best wishes,
Andreas

**Pull request merged**
