### PR TITLE
Issue 316 360 rename shared libs

### PR DESCRIPTION
**Pull request by bioinformed**
Implement issue #316 to change all Cython modules to have a `lib` prefix.  This is an alternative way to correct issue #360.  Tested on Linux and OSX with Python 2.7.12, 3.4.5, and 3.5.2 with Cython 0.24.1 and 0.25.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
This looks like it cleans up a lot of redundant special-case code, which IMHO is a big win for maintainability.

**Comment by bioinformed** [comment]
@AndreasHeger: The code looks good and the test suite passes, but I don't understand the TravisCI failures.  Can you please take a look when you get a chance?

**Comment by kyleabeauchamp** [comment]
OK, I wonder if this is the issue: https://github.com/pysam-developers/pysam/blob/master/run_tests_travis.sh#L135

I think in the past we had cython as an optional dependency, so we had a manual test of with and without cython installed in the CI script.  AFAIK now that might be deprecated.  Correct me if I'm wrong.

**Comment by kyleabeauchamp** [comment]
Actually that doesn't seem like it.  Hmm

**Comment by kyleabeauchamp** [comment]
Related to #260 perhaps?

**Comment by kyleabeauchamp** [comment]
I stared at the setup script some more and it indeed strange that "pysam/libchtslib.pyx" is claimed to be missing and tripping the "no cython" code path.  

Do we need to support both cython and nocython builds?  IMHO it would be great to reduce the number of code paths in `setup.py` and in the CI tests.  One step in that direction would be to make cython a hard dependency and simplify the build.

**Comment by AndreasHeger** [comment]
Thanks both, I will have a look now.

**Comment by AndreasHeger** [comment]
Hi @bioinformed and @kyleabeauchamp. The issue was that the travis script ran:

```
python setup.py sdist
...
pip install pysam-xxx.tar.gz
```

However, the dist command does not cythonize .pyx files into .c. The fix was to run:

```
python setup.py build sdist
...
pip install pysam-xxx.tar.gz
```

I am not sure why it used to work. Could be that .c files were accidentally part of the repos or this might be change with the cython 0.25 builder?

**Comment by AndreasHeger** [comment]
@bioinformed, many thanks for the refactoring!

**Pull request merged**
