### PR TITLE
Fix EOF issue, part 3

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
I re-ran the import scripts using the following commands, starting from the branch in #706:

```
tar -jxvf htslib-1.9.tar.bz2

rm -rf htslib
mv htslib-1.9 htslib
echo '#define HTS_VERSION "1.9"' > htslib/version.h

tar -jxvf samtools-1.9.tar.bz2


rm -rf samtools
python devtools/import.py samtools samtools-1.9/
echo '#define SAMTOOLS_VERSION "1.9"' > samtools/version.h

tar -jxvf bcftools-1.9.tar.bz2

rm -rf bcftools
python devtools/import.py bcftools bcftools-1.9
echo '#define BCFTOOLS_VERSION "1.9"' > bcftools/version.h

# Manually edit pysam/version.py
# Revert a couple of changed files to master
git checkout htslib/htslib.pc.tmp
git checkout bcftools/config.h

# Manually comment out two problematic bam_tview_main lines in samtools/bamtk.c.pysam.c
```

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
@AndreasHeger hopefully after this (assuming you agree with the approach) we're pretty close to a release.

**Comment by AndreasHeger** [comment]
Thanks!

**Comment by AndreasHeger** [comment]
@kyleabeauchamp  - may I add you to the pysam-developer group? 

This will enable you to merge pull requests. I don't have much time at the moment and your help in getting new pysam releases out and moving it along with htslib is very much appreciated. On the other hand, I am sure you also have already a lot of things on your plate.

**Comment by kyleabeauchamp** [comment]
SGTM.  Are you ready for a release?  If so, I'll add the release to github and then build the bioconda packages.

**Comment by AndreasHeger** [comment]
Great!
Yes, I am fine to release. I had hoped to look at some of the issues that have accumulated, but won't be able to do much and will be away on holidays soon.

**Pull request merged**
