### PR TITLE
More travis fixes

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
1.  Add py37 to Travis matrix
2.  Remove python 3.4 and 3.5 from Travis matrix, as they are no longer supported on Bioconda and conda-forge
3.  Clean up conda channel setup to match https://bioconda.github.io/
4.  Fix samtools version used by Travis
5.  Force ncurses to come from `conda-forge` channel to overcome various known issues.

This PR combines #782 and #784.  I wanted to kick off the CI to see if it uncovers anything.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Sorry I erased your commit history @jmarshall...it was faster to copy-paste than to lookup the git manual ;)

**Comment by kyleabeauchamp** [comment]
According to the logs, the key question is still the ncurses stuff:

```
samtools faidx ex1.fa
dyld: Symbol not found: _stdscr
  Referenced from: /Users/travis/miniconda3/envs/testenv/bin/samtools
  Expected in: /Users/travis/miniconda3/envs/testenv/bin/../lib/libncursesw.6.dylib
 in /Users/travis/miniconda3/envs/testenv/bin/samtools
make: *** [ex1.fa.fai] Abort trap: 6
```

**Comment by jmarshall** [comment]
Yes indeed. This is the external samtools that run_tests_travis.sh conda-installs. It should be getting the conda-forge ncurses package, but appears to be getting the defaults one.

It would be fairly simple to make the bioconda samtools package work with either channel's ncurses package. Or hopefully we can make run_tests_travis.sh select conda-forge's. I, for one, am rapidly losing interest in sorting out conda problems…

**Comment by kyleabeauchamp** [comment]
So my latest commit seems to overcome the `dyld` error, but still doesn't find binary equality of the test files.

**Comment by jmarshall** [comment]
> So my latest commit seems to overcome the dyld error

:tada:

> but still doesn't find binary equality of the test files.

It will be interesting to see whether this is another instance of #761 or whether there are some other trivial differences in the BAM stream between 1.7 and 1.9 to be worked around.

**Comment by kyleabeauchamp** [comment]
So it seems like the debug print statements are printing the same text, at least in the Travis output log...I'm officially lost.

**Comment by kyleabeauchamp** [comment]
OK I've reverted the debug print statements in the previous commit.  I think this PR is probably a big improvement to the Travis CI tools, but I don't know how to fix the test failures-

**Comment by jmarshall** [comment]
You can tell that the test failures are related, as most of the configurations [used to succeed](https://travis-ci.org/pysam-developers/pysam/builds/512462684). I'm pretty sure this is just more #761 and should have time to look at it over the weekend if you don't get there first.

**Comment by jmarshall** [comment]
Confirmed. I've got a branch that finally passes these tests locally that I'll push soon.

**Comment by jmarshall** [comment]
Superseded by #789.

**Pull request closed without merging**
