### PR TITLE
Fix Travis samtools etc versions and BAM comparisons

### PR DESCRIPTION
**Pull request by jmarshall**
1. Use `checkGZBinaryEqual` to compare BAM files, as the more recent samtools build likely uses libdeflate rather than zlib — which introduces spurious differences in the compressed streams.

2. Bump the samtools/htslib/bcftools versions used. Pinning 1.7 means Pysam testing is stuck forever at the broken-openssl/libcrypto condapocalypse.

3. Force ncurses to come from conda-forge channel to overcome various known issues.

4. Add py37 to Travis matrix

5. Remove python 3.4 and 3.5 from Travis matrix, as they are no longer supported on Bioconda and conda-forge

6. Clean up conda channel setup to match https://bioconda.github.io/

7. Use raw strings for regular expressions to avoid Python 3.7 "DeprecationWarning: invalid escape sequence".

### CODE REVIEW

**Comment by jmarshall** [comment]
Another attempt at #786 et al. Another commit to come (so don't merge this yet!) — I wanted to observe what travis does at this point as well.

**Comment by jmarshall** [comment]
All tests passing; I think this is ready to be merged to sort out the Travis baseline.

**Comment by kyleabeauchamp** [comment]
Thanks for brining this to the finish line.  I'm merging this now rather than waiting for the usual "release cycle mass merge" because I think it's important for the Travis tests to be behaving the way we want as people open PRs---and the existing CI script is clearly not doing the right thing.

**Comment by jmarshall** [comment]
Yes, exactly. Now to rebase my other PRs…

**Pull request merged**
