### PR TITLE
Update imports to htslib/samtools/bcftools 1.10.x

### PR DESCRIPTION
**Pull request by jmarshall**
Import htslib 1.10.2, samtools 1.10, and bcftools 1.10.2. Rearrange how _*/version.h_ are imported (now collected by _import.py_ into one _pysam/version.h_ file) and apply the `bam_tview_main()` fix automatically in _import.py_.

Further update by:

* Backporting samtools/samtools#1208 to prevent crashes in `pysam.samtools.depth()`
(or however that wrapper is called!)

* Adding recent samtools/bcftools subcommands, and removing the outdated `samimport`
(it would be possible to implement it within pysam in terms of the corresponding `view` command, but this PR currently follows samtools's lead and just removes it)

* Cherry-picking @mr-c's 790fd114aa8d27c795f94d6b4ddfb9331217b5bd from PR #870 which makes pysam work against an externally supplied _libhts.so_, which (as of 1.10) no longer allows hidden functions like `hts_useek()` to be called from outwith the library.

### CODE REVIEW

**Comment by kevinjacobs-progenity** [comment]
@jmarshall: Nice work!  I'll start testing.

**Comment by jmarshall** [comment]
@AndreasHeger @kevinjacobs-progenity @bioinformed @kyleabeauchamp: I appreciate that basically none of us have time for anything under the present circumstances :worried: but is anyone likely to have a chance to look at this?

**Comment by kevinjacobs-progenity** [comment]
I did a fair amount of testing before I ran into some minor problems and became distracted by work and committee obligations.  I'll set aside some time this weekend and finish up.  Thanks for the gentle prod.

**Comment by AndreasHegerGenomics** [comment]
Thanks, @kevinjacobs-progenity , and apologies @jmarshall , homeschooling three kids and doing the day-job at night. If you could take it further that would be great.

**Comment by AndreasHeger** [comment]
I am testing now.

**Comment by AndreasHeger** [comment]
Many thanks, @jmarshall , I will merge.

**Pull request merged**
