### PR TITLE
[WIP] Debugging conda recipe

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
So the conda recipe in the CI has still been failing.  This starts by making it easier to detect the failure.   Will debug from there...

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Remaining issues are likely LD / DYLD library path issues or rpath issues.  I see the same behavior locally with anaconda, so we might be able to sidestep travis issues by building locally.


```
===== testing package: pysam-0.8.5-py27_0 =====
import: 'pysam'
Traceback (most recent call last):
  File "/home/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import pysam
  File "/home/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.cutils import *
ImportError: libchtslib.so: cannot open shared object file: No such file or directory
TESTS FAILED: pysam-0.8.5-py27_0
```

**Comment by kyleabeauchamp** [comment]
The thing that confuses me is that conda recipe works totally fine for 0.8.4, but fails for 0.8.5.  It's something about the way the linker is being used.  For example, if you inspect a SO file for 0.8.4, you see something like this:

```
@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

However, if you look at the 0.8.5 build with otool, you see:

```
/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pysam/cvcf.so:
	@rpath/python2.7/site-packages/pysam/cvcf.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/pysam-0.8.5-py2.7-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
/Users/travis/miniconda3/envs/_test/lib/python2.7/site-packages/pysam/libchtslib.so:
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by AndreasHeger** [comment]
Thanks. I will need to setup an environment to be able to contribute. I am keen to release, but do you think I should hold off?

**Comment by kyleabeauchamp** [comment]
I'm fine with releasing as long as you're potentially willing to roll out a bugfix release if that ends up being necessary to get the conda builds working.

**Comment by kyleabeauchamp** [comment]
In fact, if you roll out the release, I'll probably ask the bioconda folks to take a stab at getting the builds to work...

**Comment by kyleabeauchamp** [comment]
I think it is definitely the RPATH stuff.  The thing to notice is that the rpath naming is inconsistent in the conda-built SO files.  I wonder if this has to do with our "pip detection" stuff in cy_build.py.  

pysam 0.8.5 Built with conda-build:
```
otool -L *.so|grep libchtslib
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
libchtslib.cpython-35m-darwin.so:
	@rpath/python3.5/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)

```

Without using the conda recipe, we have (pysam 0.8.5):

```
otool -L *.so|grep libchtslib
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
libchtslib.cpython-35m-darwin.so:
	@rpath/pysam-0.8.5-py3.5-macosx-10.5-x86_64.egg/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
```

pysam 0.8.4, conda-build
```

otool -L *.so
calignedsegment.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
calignmentfile.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
cbcf.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
cfaidx.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
csamfile.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
csamtools.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
ctabix.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
ctabixproxies.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
cutils.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
cvcf.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libchtslib.so:
	@rpath/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by AndreasHeger** [comment]
>I'm fine with releasing as long as you're potentially willing to roll out a bugfix release if that ends up being necessary to get the conda builds working.

Thanks, certainly!

**Comment by kyleabeauchamp** [comment]
Subsumed by #248

**Pull request closed without merging**
