### PR TITLE
Major fixes for writing genotypes

### PR DESCRIPTION
**Pull request by bioinformed**
Major bug fixes to setting genotyhpe (GT) values. Minor update to newest Cython and update cbcf to use new @property syntax.

### CODE REVIEW

**Comment by AndreasHeger** [comment]
Great, many thanks! Please feel free to merge whenever you think it is complete, don't let me hold you up.

**Comment by bioinformed** [comment]
I don't think I have permissions to merge PRs.  Also, this one has a
complication-- the CI system needs to update to Cython >=0.24, since I've
started using some of the new functionality since Cython 0.22.

Thanks,
-Kevin

**Comment by AndreasHeger** [comment]
Apologies, this was an oversight - you are now an 'owner'.

**Comment by AndreasHeger** [comment]
Looks like this affects only python3.3. Cython 0.24.1 is only available for python 3.4 and 3.5 on the conda channel. It seems that anaconda dropped support for version 3.3, see

http://conda.pydata.org/docs/py2or3.html#create-python-2-or-3-environments

Maybe we should do so too.

**Comment by kyleabeauchamp** [comment]
SGTM.  For Bioconda packaging, 3.3 seems to have been disabled: https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml

**Pull request merged**
