### PR TITLE
Fix deprecation warning in travis pip setup

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
See pip release notes: https://pip.pypa.io/en/stable/news/

**Comment by kyleabeauchamp** [comment]
I think this is ready to merge.  It future-proofs the CI script against a pending change in the pip command-line options.  It also cleans up a deprecation warning in the current CI output logs.

**Comment by bioinformed** [comment]
Is this work likely to fix the CI failures I observed with the library
renaming PR?

**Comment by kyleabeauchamp** [comment]
I highly doubt it.  However, if you look at my other PR #369, the latest Linux build therein reproduces the error that you observe (in a much more minimal changeset).

**Comment by AndreasHeger** [comment]
Thanks, @kyleabeauchamp

**Pull request merged**
