### PR TITLE
[WIP] Try using anaconda to run travis tests on OSX

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
@AndreasHeger  this almost works. If you look deeply in the OSX logs, the tests are actually failing due to linker import errors similar to what I found in #231

**Comment by kyleabeauchamp** [comment]
```
gcc -undefined dynamic_lookup -L/Users/travis/miniconda3/envs/testenv/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.4/pysam/csamfile.o build/temp.macosx-10.5-x86_64-3.4/pysam/htslib_util.o build/temp.macosx-10.5-x86_64-3.4/pysam/samfile_util.o build/temp.macosx-10.5-x86_64-3.4/samtools/kprobaln.o -Lpysam -L. -Lbuild/lib.macosx-10.5-x86_64-3.4/pysam -Lbuild/lib.macosx-10.5-x86_64-3.4/pysam -L/Users/travis/miniconda3/envs/testenv/lib -lz -lcurl -lcrypto -lchtslib.cpython-34m -o build/lib.macosx-10.5-x86_64-3.4/pysam/csamfile.so -dynamiclib -rpath /Users/travis/miniconda3/envs/testenv/lib/python3.4/site-packages -Wl,-headerpad_max_install_names -Wl,-install_name,@rpath/pysam-0.8.5-py3.4-macosx-10.5-x86_64.egg/pysam/csamfile.so -Wl,-x
ld: library not found for -lchtslib.cpython-34m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'gcc' failed with exit status 1
```

**Comment by bioinformed** [comment]
I think I fixed the linker problem on OS X in PR #233.

**Comment by kyleabeauchamp** [comment]
I just merged in your changes but still see linker issues here: https://travis-ci.org/pysam-developers/pysam/jobs/111003944

**Comment by bioinformed** [comment]
My changes only fixed the linker problem under Python 3.5.  It looks like you're using Python 3.3.  I also saw linker failures on Python 3.4 using that approach and was unable to spend anymore time to track them down.  Any chance you can try with Python 3.5?

**Comment by bioinformed** [comment]
n/m.  I see that Travis is testing multiple versions.

**Comment by kyleabeauchamp** [comment]
When I get home tonight I'll look through your PR to see if I can figure anything else out.

**Comment by bioinformed** [comment]
Good news is that Python 3.5 worked.  Check out these lines in setup.py:

```python
    if IS_PYTHON3:
        import sysconfig
        if sys.version_info.minor >= 5:
            internal_htslib_libraries = ["chtslib.{}".format(
                sysconfig.get_config_var('SOABI'))]
        else:
            # KBJ: This doesn't work for me on OS X with Python 3.4.  Libs have no platform tags.
            internal_htslib_libraries = ["chtslib.{}{}".format(
                sys.implementation.cache_tag,
                sys.abiflags)]
    else:
        internal_htslib_libraries = ["chtslib"]
```

**Comment by kyleabeauchamp** [comment]
Actually, even the ones that "appear" to work are having some LD library path issues that I'll fix later---probably just need to set environment variables.  For example, py35 on OSX: https://travis-ci.org/pysam-developers/pysam/jobs/111003946:L2484#L2530

**Comment by kyleabeauchamp** [comment]
FWIW, it's probably a bug in our CI if linker errors are happening silently and still giving green lights on Travis...

**Comment by AndreasHeger** [comment]
Hi @kyleabeauchamp, this is great work. Should I merge it?

Best wishes,
Andreas

**Comment by kyleabeauchamp** [comment]
Well, it's still not building successfully on all platforms.  Let me fiddle with things a bit more tonight and get back to you.

**Comment by AndreasHeger** [comment]
Thanks!

**Comment by kyleabeauchamp** [comment]
Actually, the current build for linux has some test failures that could be related to your latest commits:

```
test_get_aligned_pairs (AlignedSegment_test.TestAlignedSegment) ... FAIL
test_get_aligned_pairs_hard_clipping (AlignedSegment_test.TestAlignedSegment) ... ok
test_get_aligned_pairs_match_mismatch (AlignedSegment_test.TestAlignedSegment) ... ok
test_get_aligned_pairs_padding (AlignedSegment_test.TestAlignedSegment) ... ok
test_get_aligned_pairs_skip (AlignedSegment_test.TestAlignedSegment) ... ok
test_get_aligned_pairs_soft_clipping (AlignedSegment_test.TestAlignedSegment) ... ok
testAsString (AlignedSegment_test.TestAsString) ... ok
testCopy (AlignedSegment_test.TestCopy) ... ok
testDeepCopy (AlignedSegment_test.TestCopy) ... ok
testAddTags (AlignedSegment_test.TestTags) ... ok
testAddTagsType (AlignedSegment_test.TestTags) ... ok
testEmptyTag (AlignedSegment_test.TestTags) ... ok
testMDTag (AlignedSegment_test.TestTags) ... ./run_tests_travis.sh: line 89:  6558 Segmentation fault      (core dumped) nosetests -s -v
```

**Comment by kyleabeauchamp** [comment]
Note that the build has nosetest failures but still reports travis success, which is not quite right either...

**Comment by AndreasHeger** [comment]
Thanks. Seems I broke the unit tests on travis.

**Comment by kyleabeauchamp** [comment]
Almost there: with the latest changes from master, I'm down to the following:

```

======================================================================
ERROR: testConstructionFromCopy (VariantFile_test.TestConstructionVCFGZWithContigs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 335, in testConstructionFromCopy
    vcf_in = pysam.VariantFile(fn_in)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf42_withcontigs.vcf.gz` not found
======================================================================
ERROR: testConstructionWithLines (VariantFile_test.TestConstructionVCFGZWithContigs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 349, in testConstructionWithLines
    vcf_in = pysam.VariantFile(fn_in)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf42_withcontigs.vcf.gz` not found
======================================================================
ERROR: testConstructionWithRecords (VariantFile_test.TestConstructionVCFGZWithContigs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 313, in testConstructionWithRecords
    vcf_in = pysam.VariantFile(fn_in)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf42_withcontigs.vcf.gz` not found
======================================================================
ERROR: testConstructionFromCopy (VariantFile_test.TestConstructionVCFGZWithoutContigs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 335, in testConstructionFromCopy
    vcf_in = pysam.VariantFile(fn_in)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf42.vcf.gz` not found
======================================================================
ERROR: testConstructionWithLines (VariantFile_test.TestConstructionVCFGZWithoutContigs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 349, in testConstructionWithLines
    vcf_in = pysam.VariantFile(fn_in)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf42.vcf.gz` not found
======================================================================
ERROR: testConstructionWithRecords (VariantFile_test.TestConstructionVCFGZWithoutContigs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 313, in testConstructionWithRecords
    vcf_in = pysam.VariantFile(fn_in)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf42.vcf.gz` not found
======================================================================
ERROR: testOpen (VariantFile_test.TestIndexFilename)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 292, in testOpen
    v = pysam.VariantFile(fn, index_filename=idx_fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testAlleles (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 204, in testAlleles
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testAlt (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 198, in testAlt
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testChrom (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 162, in testChrom
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testFilter (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 216, in testFilter
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testFormat (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 233, in testFormat
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testId (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 186, in testId
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testInfo (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 222, in testInfo
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testPos (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 168, in testPos
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testQual (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 210, in testQual
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testRef (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 192, in testRef
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testSampleAlleleIndices (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 274, in testSampleAlleleIndices
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testSampleAlleles (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 243, in testSampleAlleles
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testSampleFormats (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 254, in testSampleFormats
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testStart (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 174, in testStart
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
ERROR: testStop (VariantFile_test.TestParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 180, in testStop
    v = pysam.VariantFile(fn)
  File "pysam/cbcf.pyx", line 3266, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:47997)
  File "pysam/cbcf.pyx", line 3435, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:50304)
  File "pysam/cbcf.pyx", line 3492, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51160)
IOError: file `cbcf_data/example_vcf40.vcf.gz` not found
======================================================================
FAIL: testVCFGZ (VariantFile_test.TestMissingGenotypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 55, in testVCFGZ
    self.check(self.filename + ".gz")
  File "/home/travis/build/pysam-developers/pysam/tests/VariantFile_test.py", line 39, in check
    self.assertEqual(True, os.path.exists(fn))
AssertionError: True != False
----------------------------------------------------------------------
Ran 786 tests in 90.309s
FAILED (errors=22, failures=1)
3270 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
3235 + 0 mapped (98.93% : N/A)
3270 + 0 paired in sequencing
1636 + 0 read1
1634 + 0 read2
3124 + 0 properly paired (95.54% : N/A)
3124 + 0 with itself and mate mapped
111 + 0 singletons (3.39% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by AndreasHeger** [comment]
Thanks, this is down to me. I will fix it tonight and merge.

Best wishes,
Andreas

**Comment by kyleabeauchamp** [comment]
Actually i still need to fix a few more issues with osx before merging this.

**Comment by kyleabeauchamp** [comment]
OK, I disabled libcurl on travis and it now seems to build OK on OSX.  There are still some test failures, however, similar to what I show below. 

```
======================================================================
ERROR: testWrite (tabix_test.VCFFromTabixTest_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/pysam-developers/pysam/tests/tabix_test.py", line 733, in setUp
    TestVCF.setUp(self)
  File "/Users/travis/build/pysam-developers/pysam/tests/tabix_test.py", line 684, in setUp
    shutil.copyfile(self.filename, self.tmpfilename)
  File "/Users/travis/miniconda3/envs/testenv/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 24] Too many open files: 'tmp_4377947920.vcf'
======================================================================
ERROR: testRead (tabix_test.VCFFromTabixTest_20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/pysam-developers/pysam/tests/tabix_test.py", line 733, in setUp
    TestVCF.setUp(self)
  File "/Users/travis/build/pysam-developers/pysam/tests/tabix_test.py", line 684, in setUp
    shutil.copyfile(self.filename, self.tmpfilename)
  File "/Users/travis/miniconda3/envs/testenv/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 24] Too many open files: 'tmp_4377727056.vcf'
```

**Comment by kyleabeauchamp** [comment]
Actually, there are build issues on py3K python versions on OSX.  Py27 builds fine but dies during tests.

```
ld: library not found for -lchtslib.cpython-34m
```

**Comment by AndreasHeger** [comment]
Thanks. I will check for open without close cases.

**Comment by AndreasHeger** [comment]
Thanks! As all linux tests pass, I will now merge and comment out  the osx section to be fixed in a separate branch.

**Comment by kyleabeauchamp** [comment]
Sounds good.  Note that I also added the bioconda recipe to this pull request.  I figured I might as well try to get that working as well.

**Comment by kyleabeauchamp** [comment]
PS: if you open a [WIP] pull request with your OSX branch, I can try to comment on any travis failures that you see.

**Pull request merged**
