### PR TITLE
Added tests for some samtools wrapped functionality

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Here are some basic tests covering the issues I found.

**Comment by kyleabeauchamp** [comment]
Here's the output:

```
nosetests test_samtools_python.py -s -v
test_samtools_python.test_idxstats_parse ... ERROR
test_samtools_python.test_bedcov ... FAIL

======================================================================
ERROR: test_samtools_python.test_idxstats_parse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "~/src/pysam/tests/test_samtools_python.py", line 7, in test_idxstats_parse
    _seqname, _seqlen, nmapped, _nunmapped = line.split()
ValueError: need more than 1 value to unpack

======================================================================
FAIL: test_samtools_python.test_bedcov
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "~/src/pysam/tests/test_samtools_python.py", line 15, in test_bedcov
    assert len(fields) in [4, 5], "bedcov should give tab delimited output with 4 or 5 fields.  Split line (%s) gives %d fields." % (fields, len(fields))
AssertionError: bedcov should give tab delimited output with 4 or 5 fields.  Split line (['c']) gives 1 fields.

----------------------------------------------------------------------
Ran 2 tests in 0.008s

FAILED (errors=1, failures=1)

```

**Comment by kyleabeauchamp** [comment]
Actually, these tests are somewhat of a dupe of #245 

However, they're still probably useful tests, pending the outcome of how we deal with legacy vs. new-style output.

**Comment by kyleabeauchamp** [comment]
I added tests for both new and old style output, with the assumption that we add some flag for switching between the two.  

I believe the old-style output tests will still pass on pysam 0.8.4

**Comment by kyleabeauchamp** [comment]
I am *not* recommending that we use the name `old_style_output` for the kwarg--consider it a placeholder...

**Comment by AndreasHeger** [comment]
ahh, sorry, just catching up!

**Comment by kyleabeauchamp** [comment]
I updated the kwarg to be `split_lines`.

**Comment by kyleabeauchamp** [comment]
Also, I have confirmed that the tests behave as expected on pysam 0.8.4 and 0.9

```
0.8.4

test_samtools_python.test_idxstats_parse_split_lines ... ok
test_samtools_python.test_bedcov_split_lines ... ok
test_samtools_python.test_idxstats_parse ... ERROR
test_samtools_python.test_bedcov ... ERROR


0.9.0

test_samtools_python.test_idxstats_parse_split_lines ... ERROR
test_samtools_python.test_bedcov_split_lines ... FAIL
test_samtools_python.test_idxstats_parse ... ok
test_samtools_python.test_bedcov ... ok
```

**Comment by AndreasHeger** [comment]
Thanks, I have currently limited time, will get to it this weekend.
Best,
Andreas

**Pull request merged**
