### PR TITLE
Add index filename specification to VariantFile API

### PR DESCRIPTION
**Pull request by bioinformed**
Addresses issue #87 for @jeromekelleher

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This looks great, thanks @bioinformed.

**Comment by AndreasHeger** [comment]
Thanks! I will wait for a few days for more feed-back and then release.

**Comment by bioinformed** [comment]
I'm working on adding more read/write functionality to cbcf over the next
few days.  I'll keep pushing pure bug fixes and will see how stable the new
features are before sending a pre-release PR.

-Kevin

**Comment by AndreasHeger** [comment]
That's great, thanks!

**Pull request merged**
