### PR TITLE
Update imports to htslib/samtools/bcftools 1.13

### PR DESCRIPTION
**Pull request by jmarshall**
Import htslib, samtools, and bcftools 1.12:

* Really fix bugs like #928 (when both samtools and bcftools have a command implemented by functions with the same name) by adding _import.py_ infrastructure to rename one of them. Apply it to `main_reheader()`.

* Have _import.py_ automatically update the version numbers in the documentation, as this is easily forgotten.

* HTSlib and samtools 1.12 have added infrastructure to report the compilation flags used to build them. We add an equivalent of that to _setup.py_ so that it reports the compilation flags used by the Python build processes.

* Finally import the 1.12 releases, and add the new `version` subcommand to _pysam/samtools.py_.

Updated to import htslib, samtools, and bcftools 1.13:

* Disable `flagstat` test as the output has acquired a few extra lines in samtools-1.13.

* A couple of other updates, as noted in the commit messages.

* Import the 1.13 releases, and add the new `import` subcommand to _pysam/samtools.py_ (as `fqimport`).

* Backport samtools/samtools#1465, which fixes a crash when using `pysam.samtools.depth(…)`.

### CODE REVIEW

**Comment by jmarshall** [comment]
The next htslib/samtools/etc release is now imminent, and htslib 1.12 has a serious bug with region queries (which is thought to have been fixed in the upcoming release).

This PR has some complexity in the _setup.py_ changes to create the _config_vars.h_ headers, so it would be good for that part to see some review. However it would be good to run the import again to update to the upcoming htslib/samtools/etc releases quickly after (or during!) merging this.

**Comment by jmarshall** [comment]
Now updated to htslib/samtools/bcftools 1.13 as released today.

@AndreasHeger @kevinjacobs-progenity: I'd quite like to merge this next week — there's only so many balls I want to have in the air at once, and with this merged it will be simpler to get on with some other improvements that touch the same files. Does anyone want to cast an eye over this?

This has passed testing with the range of Python versions as can [be seen here](https://github.com/jmarshall/pysam/actions/runs/1015504308).

**Comment by kevinjacobs-progenity** [comment]
Many thanks!  This is extremely important and timely work.  I'll run some of my own tests this weekend and let you know if I find any problems.  Beyond that, @AndreasHeger is still sole keeper for the release process, as far as I know.

**Comment by jmarshall** [comment]
Re “timely”, it's a shame I did 90% of the 1.12 import in April but only finished it up earlier this week :smile:

Thanks for your upcoming testing. Agree re who's in charge of releases; and I have a few more things I want to get in before we get to that stage in any case.

**Comment by AndreasHeger** [comment]
Hi, really sorry I am not able to contribute much at the moment. I am still happy to do the release, but if anybody else would like to take care of it, I am happy to share anything that is necessary to do so.

**Comment by AndreasHeger** [comment]
And of course many thanks to @jmarshall for keeping pysam afloat.

**Comment by jmarshall** [comment]
I'll aim to merge this this week, to facilitate carrying on with other things. If any problems eventuate, we will be able to fix them on **master**.

**Comment by kevinjacobs-progenity** [comment]
I've run my local test suite and all looks good.  Thanks, @jmarshall.

**Comment by jmarshall** [comment]
Excellent — thanks, I'll hit the button today.

**Pull request merged**
