### PR TITLE
Ensure "python setup.py sdist" cythonizes extension modules

### PR DESCRIPTION
**Pull request by marcelm**
I saw that it is currently necessary to run `python setup.py build` before `sdist` to ensure that the generated tarball contains cythonized sources. This means that generating the tarball creates a couple of minutes.

With this PR, `python setup.py sdist` will cythonize the sources before bundling the tarball. This takes only a couple of seconds.

My intention is to use this in the CI tests: It would be nice to generate the tarball in a separate job (with the development dependencies installed), and then start a new job to install it (without developer dependencies installed). This more closely resembles what happens on a user’s system.

If Cython isn’t installed, `python setup.py sdist` will raise an ImportError when running `python setup.py sdist`. IMO the resulting error message (`ModuleNotFoundError: No module named 'Cython'`) is clear enough, but I could add a `if HAVE_CYTHON` guard if you think this would be better.

### CODE REVIEW

**Comment by jmarshall** [comment]
Something like this is probably a good idea if it is desired that `sdist` produces a tarball containing Cython _pysam/*.c_ files.

However I'm not convinced this is the appropriate approach for the basic CI. IMHO the natural CI to run on pushes to **master** and PRs is a matrix of `pythonX.Y setup.py build && pytest` jobs.

Producing a tarball and ensuring that that builds well is a different category of CI; one that would naturally run primarily when tags are created.

**Comment by marcelm** [comment]
Sure, let’s discuss what to do in which CI job separately. Even if this only is used in a "deploy" job (or just on the command line for that matter), it improves the situation.

**Comment by jmarshall** [comment]
It took me a while to understand what was going on here and why it's good to unconditionally rerun the cythonisation during `sdist`, but the penny finally dropped. By then I had simplified it to not need the global `extensions` variable. Thanks!

**Comment by marcelm** [comment]
Thanks for merging, and avoiding the global is much better :-).

**Pull request merged**
